/**
 * Stage 5 — packing (§8.5). Generates levels and writes them as 25-level JSON packs
 * aligned to the level-select pager, plus the loader map the app requires from.
 *
 *   node --import ./tools/register.mjs tools/generateLevels.ts [--from 1] [--to 500]
 *
 * Regenerating a range rewrites only the packs it touches, so a curve tweak in one
 * band does not churn the whole 1.4MB of committed data.
 */
import {mkdirSync, readFileSync, writeFileSync} from 'node:fs';
import {join} from 'node:path';
import {packLevel} from '../src/game/levels/codec.ts';
import type {LevelPack} from '../src/game/levels/codec.ts';
import {generateLevel} from './pipeline/generate.ts';
import type {GenerationReport} from './pipeline/generate.ts';
import {planLevel} from './pipeline/plan.ts';

const PACK_SIZE = 25;
const TOTAL_LEVELS = 500;
const PACKS_DIR = join(
  import.meta.dirname,
  '..',
  'src',
  'game',
  'levels',
  'packs',
);
const LOADERS_FILE = join(
  import.meta.dirname,
  '..',
  'src',
  'game',
  'levels',
  'packLoaders.ts',
);

function arg(name: string, fallback: number): number {
  const at = process.argv.indexOf(`--${name}`);
  return at >= 0 && process.argv[at + 1]
    ? Number(process.argv[at + 1])
    : fallback;
}

const packName = (packIndex: number): string => {
  const from = packIndex * PACK_SIZE + 1;
  const to = from + PACK_SIZE - 1;
  return `pack_${String(from).padStart(3, '0')}_${String(to).padStart(
    3,
    '0',
  )}.json`;
};

function readExistingPack(packIndex: number): LevelPack | null {
  try {
    return JSON.parse(
      readFileSync(join(PACKS_DIR, packName(packIndex)), 'utf8'),
    );
  } catch {
    return null;
  }
}

function writeLoaders(): void {
  const packCount = Math.ceil(TOTAL_LEVELS / PACK_SIZE);
  const lines: string[] = [
    '/**',
    ' * Generated by tools/generateLevels.ts — do not edit by hand.',
    ' *',
    ' * Each entry is a thunk so Metro keeps the pack out of the initial bundle',
    ' * evaluation; src/game/levels/index.ts holds three packs resident and drops the',
    ' * rest (§8.5).',
    ' */',
    '',
    'export const PACK_LOADERS: (() => unknown)[] = [',
  ];
  for (let i = 0; i < packCount; i++) {
    lines.push(`  () => require('./packs/${packName(i)}'),`);
  }
  lines.push('];', '');
  writeFileSync(LOADERS_FILE, lines.join('\n'), 'utf8');
}

function main(): void {
  const from = arg('from', 1);
  const to = arg('to', TOTAL_LEVELS);
  mkdirSync(PACKS_DIR, {recursive: true});

  const startedAt = Date.now();
  const reports = new Map<number, GenerationReport>();
  const failures: number[] = [];

  for (let id = from; id <= to; id++) {
    const slot = planLevel(id);
    const report = generateLevel(slot);
    if (!report) {
      failures.push(id);
      process.stdout.write(`\nlevel ${id}: FAILED to generate\n`);
      continue;
    }
    reports.set(id, report);

    if (id % 10 === 0 || id === to) {
      const elapsed = ((Date.now() - startedAt) / 1000).toFixed(0);
      const done = id - from + 1;
      const rate = done / Math.max(1, Number(elapsed));
      const remaining = Math.round((to - id) / Math.max(0.001, rate));
      process.stdout.write(
        `\r${id}/${to}  ${elapsed}s elapsed  ~${remaining}s left  ` +
          `last: ${report.shape} n=${report.level.arrows.length} ` +
          `D=${report.level.difficulty.toFixed(2)} (target ${slot.targetD})   `,
      );
    }
  }
  process.stdout.write('\n');

  const firstPack = Math.floor((from - 1) / PACK_SIZE);
  const lastPack = Math.floor((to - 1) / PACK_SIZE);
  for (let packIndex = firstPack; packIndex <= lastPack; packIndex++) {
    const packFrom = packIndex * PACK_SIZE + 1;
    const packTo = packFrom + PACK_SIZE - 1;
    const existing = readExistingPack(packIndex);
    const levels = [];
    for (let id = packFrom; id <= packTo; id++) {
      const report = reports.get(id);
      if (report) {
        levels.push(packLevel(report.level));
      } else {
        const kept = existing?.levels.find(l => l.id === id);
        if (kept) {
          levels.push(kept);
        }
      }
    }
    const pack: LevelPack = {v: 1, from: packFrom, to: packTo, levels};
    writeFileSync(
      join(PACKS_DIR, packName(packIndex)),
      `${JSON.stringify(pack)}\n`,
      'utf8',
    );
  }

  writeLoaders();

  const values = [...reports.values()];
  const offTarget = values.filter(
    r => Math.abs(r.level.difficulty - planLevel(r.level.id).targetD) > 0.4,
  );
  console.log(
    `\nwrote packs ${firstPack + 1}..${lastPack + 1} — ${
      values.length
    } levels, ` +
      `${failures.length} failures, ${offTarget.length} outside the +/-0.4 D window`,
  );
  if (failures.length > 0) {
    console.log(`failed levels: ${failures.join(', ')}`);
    process.exitCode = 1;
  }
}

main();
